Add skeleton users service using feathers-mongoose, resources doc, more
Incorporated new skeleton functionality based on the structure
created by the featherscli for the basic app and a service based
on mongoose.

Actually defining the app's transports has not been done which is why
compiling reports an error:
    src/server.ts(19,20): error TS2339: Property 'listen' does not exist on type 'Application<object>'.